"""
fabric-lint CLI entry point.

Usage:
    fabric-lint check .tool-fabric.yaml
    fabric-lint report .tool-fabric.yaml --format markdown
    fabric-lint init > .tool-fabric.yaml
"""

import sys
import json
from collections import Counter
from pathlib import Path

import click
import yaml

from . import run_checks, Registry
from .checks import Severity


SEVERITY_COLOR = {
    Severity.ERROR: "red",
    Severity.WARNING: "yellow",
    Severity.INFO: "cyan",
}

SEVERITY_LABEL = {
    Severity.ERROR: "ERROR  ",
    Severity.WARNING: "WARNING",
    Severity.INFO: "INFO   ",
}


@click.group()
@click.version_option(package_name="tool-fabric")
def cli():
    """Declarative governance for LLM tool registries."""


@cli.command()
@click.argument("registry_file", type=click.Path(exists=True))
@click.option("--min-severity", default="info", type=click.Choice(["error", "warning", "info"]),
              help="Minimum severity to report.")
@click.option("--format", "output_format", default="text", type=click.Choice(["text", "json"]),
              help="Output format.")
@click.option("--fail-on", default="error", type=click.Choice(["error", "warning", "never"]),
              help="Exit with code 1 when violations at this level or above are found.")
def check(registry_file: str, min_severity: str, output_format: str, fail_on: str):
    """Validate a .tool-fabric.yaml registry file."""
    path = Path(registry_file)

    try:
        with open(path) as f:
            raw = yaml.safe_load(f)
    except yaml.YAMLError as e:
        click.echo(f"Parse error: {e}", err=True)
        sys.exit(1)

    registry = Registry(raw, source_file=str(path))
    results = run_checks(registry)

    min_sev = Severity[min_severity.upper()]
    visible = [v for v in results if v.severity >= min_sev]

    if output_format == "json":
        click.echo(json.dumps([v.to_dict() for v in visible], indent=2))
    else:
        _print_text_report(visible, registry)

    fail_sev = {"error": Severity.ERROR, "warning": Severity.WARNING, "never": None}[fail_on]
    if fail_sev and any(v.severity >= fail_sev for v in results):
        sys.exit(1)


@cli.command()
@click.argument("registry_file", type=click.Path(exists=True))
@click.option("--format", "output_format", default="markdown", type=click.Choice(["markdown", "text"]))
def report(registry_file: str, output_format: str):
    """Generate a human-readable audit report."""
    path = Path(registry_file)

    with open(path) as f:
        raw = yaml.safe_load(f)

    registry = Registry(raw, source_file=str(path))
    results = run_checks(registry)

    if output_format == "markdown":
        click.echo(_build_markdown_report(results, registry))
    else:
        _print_text_report(results, registry)


@cli.command()
def init():
    """Print a minimal .tool-fabric.yaml template to stdout."""
    template = """\
# .tool-fabric.yaml — generated by fabric-lint init
# See https://github.com/crbazevedo/tool-fabric for full schema docs.

tools:
  example_tool:
    category: utility
    description: >
      Does X and returns Y. Use when Z.
      Do NOT use when A — prefer example_tool_alt instead.
    concepts_required: []
    alternatives: []
    composes_with: []
    input_shape:
      param_a: string
    output_shape:
      result: string
    query_tips: ""
    cost_hints:
      latency_ms: 100
      idempotent: true
      side_effects: []

concepts:
  example.concept:
    description: "A domain concept required by one or more tools."
    prerequisites: []
    examples: ["example value"]
    scope: session

patterns:
  example_pattern:
    name: "Example compound operation"
    intent_triggers:
      - "do X and then Y"
    tool_sequence:
      - example_tool
    merge_strategy: first

properties:
  mece_groups: []
  completeness_assertions: []
  coherence_rules: []
"""
    click.echo(template)


def _print_text_report(violations, registry: "Registry") -> None:
    tools = registry.raw.get("tools", {})
    patterns = registry.raw.get("patterns", {})
    concepts = registry.raw.get("concepts", {})

    click.echo(f"\ntool-fabric lint — {registry.source_file}")
    click.echo(f"  {len(tools)} tools  |  {len(patterns)} patterns  |  {len(concepts)} concepts\n")

    if not violations:
        click.secho("  No violations found.", fg="green")
        return

    errors = [v for v in violations if v.severity == Severity.ERROR]
    warnings = [v for v in violations if v.severity == Severity.WARNING]
    infos = [v for v in violations if v.severity == Severity.INFO]

    for v in violations:
        color = SEVERITY_COLOR[v.severity]
        label = SEVERITY_LABEL[v.severity]
        click.secho(f"  {label}  [{v.code}] {v.message}", fg=color)

    click.echo()
    parts = []
    if errors:
        parts.append(click.style(f"{len(errors)} error{'s' if len(errors) != 1 else ''}", fg="red"))
    if warnings:
        parts.append(click.style(f"{len(warnings)} warning{'s' if len(warnings) != 1 else ''}", fg="yellow"))
    if infos:
        parts.append(click.style(f"{len(infos)} info", fg="cyan"))
    click.echo("  " + ", ".join(parts))


def _build_markdown_report(violations, registry: "Registry") -> str:
    tools = registry.raw.get("tools", {})
    patterns = registry.raw.get("patterns", {})
    concepts = registry.raw.get("concepts", {})
    props = registry.raw.get("properties") or {}
    mece_groups = props.get("mece_groups") or []

    errors = [v for v in violations if v.severity == Severity.ERROR]
    warnings = [v for v in violations if v.severity == Severity.WARNING]
    infos = [v for v in violations if v.severity == Severity.INFO]

    lines = [
        "# tool-fabric Registry Audit",
        "",
        f"**File:** `{registry.source_file}`",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| Tools | {len(tools)} |",
        f"| Concepts | {len(concepts)} |",
        f"| Patterns | {len(patterns)} |",
        f"| MECE groups | {len(mece_groups)} |",
        f"| Errors | {len(errors)} |",
        f"| Warnings | {len(warnings)} |",
        f"| Info | {len(infos)} |",
        f"| **Total violations** | **{len(violations)}** |",
        "",
    ]

    if violations:
        code_counts = Counter(v.code for v in violations)
        severity_for = {v.code: v.severity.name for v in violations}
        lines += [
            "## Violation Breakdown",
            "",
            "| Code | Severity | Count |",
            "|------|----------|-------|",
        ]
        for code in sorted(code_counts):
            lines.append(f"| {code} | {severity_for[code]} | {code_counts[code]} |")
        lines.append("")

    def section(title, items, icon):
        if not items:
            return
        lines.append(f"## {icon} {title} ({len(items)})")
        lines.append("")
        for v in items:
            lines.append(f"- **[{v.code}]** {v.message}")
        lines.append("")

    section("Errors", errors, "🔴")
    section("Warnings", warnings, "🟡")
    section("Info", infos, "🔵")

    if not violations:
        lines.append("✅ No violations found.")

    return "\n".join(lines)


if __name__ == "__main__":
    cli()
